### GENERAL SETTINGS ###

# Site settings
title: gitdeploy.io
description: "gitdeploy.io ...."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://www.gitdeploy.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: twitter
    url: https://twitter.com/_aeneasr
  - title: github
    url: https://github.com/ory-platform/star
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Ory GmbH
    - Belfortstra√üe 14
    - 81667 Munich
    - Germany
#email: hello@solidtheme.com
#tel: +34 8493-4893


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
#  - name: Mark Webber
#    position: CEO
#    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
#    img: team01.jpg
#    social:
#      - title: envelope #use for email address
#        url: mailto:name@domain.com
#      - title: twitter
#        url: http://twitter.com/handle
    
# Clients information. Shown on Home and About pages.
clients:
#  - name: dribbble
#    img: client01.png
#  - name: Code is Poetry
#    img: client02.png
#  - name: Vimeo
#    img: client03.png
#  - name: VimeoPro
#    img: client04.png
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s."

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "Starred really helped us..."
    author: Marcel Newman
    position: XY - SERLO.ORG
